######################
## R requirements   ##
## /usr/bin/Rscript ##
######################

all:
	/usr/bin/Rscript main.R
	rm Rplots.pdf
	pdflatex trueSynergy-en.tex
	pdflatex trueskill_versionGeneral-en.tex
	pdflatex elo-en.tex
	pdflatex elo-factor-en.tex



